# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 19:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0003_auto_20170211_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=300)),
                ('code', models.TextField()),
                ('ended', models.BooleanField(default=True)),
                ('chat_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Message')),
                ('junior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='junior', to=settings.AUTH_USER_MODEL)),
                ('senior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senior', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
