# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 19:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_message_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='chat_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.Message'),
        ),
        migrations.AlterField(
            model_name='session',
            name='ended',
            field=models.BooleanField(default=False),
        ),
    ]
