# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 09:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20170311_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='senior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='senior', to=settings.AUTH_USER_MODEL),
        ),
    ]
