# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_auto_20170311_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
